registrationInterval: 250
registrationRepeateCount: 10
sessionControlInterval: 100
sessionControlRepeateCount: 10
repeateBlockCount: 10
blockControlInterval: 50 
blockControlRepeateCount: 10 
frameSendingInterval: 1
clientSessionRepeateInterval: 250
clientSessionRepeateCount: 10
clientBlockRepeateInterval: 100
clientBlockRepeateCount: 10